# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ–](bold red)"


[buf]
symbol = "ï’ "
style = "fg:#00a1ff"

[c]
symbol = "î˜ "
style = "fg:#00a1ff"

[conda]
symbol = "ï„Œ "
style = "fg:#00a1ff"

[dart]
symbol = "î˜ "
style = "fg:#00a1ff"

[git_branch]
symbol = "ï˜ "
style = "fg:#00a1ff"

[golang]
symbol = 'î˜§ '
style = "fg:#00a1ff"

[python]
symbol = "îˆµ "
python_binary = "python3"
style = "fg:#00a1ff"

[nim]
symbol = "ïš¤ "
style = "fg:#00a1ff"

[nix_shell]
symbol = "ï‹œ "
style = "fg:#00a1ff"

[nodejs]
symbol = "îœ˜ "
style = "fg:#00a1ff"

[package]
symbol = "ï£– "
style = "fg:#00a1ff"

[haskell]
symbol = "î· "
style = "fg:#00a1ff"

[hg_branch]
symbol = "ï˜ "
style = "fg:#00a1ff"

[java]
symbol = "î‰– "
style = "fg:#00a1ff"

[julia]
symbol = "î˜¤ "
style = "fg:#00a1ff"

[spack]
symbol = "ğŸ…¢ "
style = "fg:#00a1ff"

[rust]
symbol = "î¨ "
style = "fg:#00a1ff"

[directory]
read_only = " ï ½"
style = "fg:#ffffff"
truncation_length = 30
truncation_symbol = "â€¦/"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[$path]($style)[$read_only]($read_only_style) "

[git_metrics]
added_style = "#42b983"
deleted_style = "#f20c84"
format = '([+$added]($added_style))([-$deleted]($deleted_style)) '
disabled = false
